- name: gather jupiter facts
  hosts: juniper
  gather_facts: false
  vars:
    ansible_network_os: junipernetworks.junos.junos
    ansible_connection: ansible.netcommon.network_cli
    #ansible_connection: ansible.netcommon.libssh
    ansible_network_cli_ssh_type: libssh
    ansible_libssh_ssh_type: libssh
    #ansible_network_cli_ssh_type: paramiko
    ansible_libssh_password_prompt: "PASSCODE:"

  tasks:
    - name: run show version on remote devices
       #arista.eos.eos_command:
      ansible.netcommon.cli_command:
        command: show version
      register: command_output

    - name: print gathered facts
      ansible.builtin.debug:
        msg: "{{ command_output }}"
