---
- name: Use the Jupiter Device Collection
  hosts: juniper
  # connection: local
  connection: juniper.device.pyez
  gather_facts: false
  become: false
  vars:
    debug: false
    connection_info:
      host: "{{ ansible_ssh_host }}"
      port: "{{ ansible_ssh_port }}"
      user: "{{ ansible_ssh_user }}"
      passwd: "{{ ansible_ssh_pass }}"
  collections:
    - juniper.device

  tasks:
    - name: Backup the current configuration
      juniper.device.config:
        check: false
        commit: false
        dest: "/tmp/{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}_{{ inventory_hostname_short }}.config"
        diff: false
        retrieve: "committed"

    - name: Get facts using juniper.device
      when: debug == true
      juniper.device.facts:
      register: command_output

    - name: Print gathered facts
      ansible.builtin.debug:
        msg:
          - "{{ ansible_facts }}"

    - name: V-253878
      juniper.device.config:
        load: "merge"
        lines:
          - set system services netconf ssh connection-limit 10
          - set system services netconf ssh rate-limit 4
      register: response

    - name: Print the response
      when: debug == true
      ansible.builtin.debug:
        var: response

    - name: V-253879
      juniper.device.config:
        load: 'replace'
        lines:
          - "set system syslog host {{ syslog_server }} any info"
          - "set system syslog file change.log change-log info"
          - "set system syslog file interactive-cmds.log interactive-commands info"
        diff: True
      register: response

    - name: Print the response
      when: debug == true
      ansible.builtin.debug:
        var: response

    - name: V-253885
      juniper.device.config:
        load: 'replace'
        lines:
          - set system login retry-options tries-before-disconnect 3
          - set system login retry-options lockout-period 15
        diff: True
      register: response

    - name: Print the response
      when: debug == true
      ansible.builtin.debug:
        var: response

    - name: V-253886 Configure the MOTD
      juniper.device.config:
        load: 'replace'
        lines:
          - "set system login message \"You are accessing a U.S. Government (USG) Information System (IS) that is provided for USG-authorized use only.\\n\\nBy using this IS (which includes any device attached to this IS), you consent to the following conditions:\\n\\n-The USG routinely intercepts and monitors communications on this IS for purposes including, but not limited to, \\n penetration testing, COMSEC monitoring, network operations and defense, personnel misconduct (PM), law enforcement (LE),\\n and counterintelligence (CI) investigations.\\n\\n-At any time, the USG may inspect and seize data stored on this IS.\\n\\n-Communications using, or data stored on, this IS are not private, are subject to routine monitoring, interception,\\n and search, and may be disclosed or used for any USG-authorized purpose.\\n\\n-This IS includes security measures (e.g., authentication and access controls) to protect USG interests--not for your personal benefit or privacy.\\n\\n-Notwithstanding the above, using this IS does not constitute consent to PM, LE or CI investigative searching or monitoring of the content of\\n privileged communications, or work product, related to personal representation or services by attorneys, psychotherapists, or clergy,\\n and their assistants. Such communications and work product are private and confidential. See User Agreement for details.\\n\\n\\n\\n\""
        diff: True
      register: response
    
    - name: Print the response
      when: debug == true
      ansible.builtin.debug:
        var: response

    - name: V-253889
      juniper.device.config:
        load: 'replace'
        lines:
          - set system syslog host {{ syslog_server }}  any info
          - set system syslog file all.log any info
          - set system syslog time-format year
        diff: True
      register: response

    - name: Print the response
      when: debug == true
      ansible.builtin.debug:
        var: response

    # Broken - command doesn't work in my EX instance
    # - name: V-253900
    #   juniper.device.config:
    #     load: 'replace'
    #     lines:
    #       - delete system services ftp
    #       - delete system services telnet
    #       - delete system services web-management
    #     diff: True
    #   register: response

    - name: Print the response
      when: debug == true
      ansible.builtin.debug:
        var: response

    - name: V-253901
      juniper.device.config:
        load: 'replace'
        lines:
          - set system services ssh root-login deny
          - set system ports console insecure
        diff: True
      register: response

    - name: Print the response
      when: debug == true
      ansible.builtin.debug:
        var: response

    # Broken - command doesn't work in my EX instance
    # - name: V-253903
    #   juniper.device.config:
    #     load: 'replace'
    #     lines:
    #       - set system services ssh protocol-version v2
    #     diff: True
    #   register: response

    - name: Print the response
      when: debug == true
      ansible.builtin.debug:
        var: response

    - name: V-253904/5/6/7/9
      juniper.device.config:
        load: 'set'
        lines:
          - set system login password minimum-length 15
          - set system login password minimum-upper-cases 1
          - set system login password minimum-lower-cases 1
          - set system login password minimum-numerics 1
          - set system login password minimum-punctuations 1
          # - set system login password minimum-changes 8
          - set system login password format sha512
        diff: True
      register: response

    - name: Print the response
      when: debug == true
      ansible.builtin.debug:
        var: response

    - name: V-253911
      juniper.device.config:
        load: 'replace'
        lines:
          - set system services ssh ciphers aes256-ctr
          - set system services ssh ciphers aes192-ctr
          - set system services ssh ciphers aes128-ctr
          - set system services ssh macs hmac-sha2-512
          - set system services ssh macs hmac-sha2-256
          - set system services ssh key-exchange ecdh-sha2-nistp521
          - set system services ssh key-exchange ecdh-sha2-nistp384
          - set system services ssh key-exchange ecdh-sha2-nistp256
          - set system services ssh key-exchange dh-group14-sha1
          # - set system rng hmac-drbg
        diff: True
      register: response

    - name: Print the response
      when: debug == true
      ansible.builtin.debug:
        var: response

    # - name: V-
    #   juniper.device.config:
    #     load: 'replace'
    #     lines:
    #       - 
    #     diff: True
    #   register: response

    # - name: Print the response
    #   when: debug == true
    #   ansible.builtin.debug:
    #     var: response

...


