- name: gather jupiter facts
  hosts: juniper
  gather_facts: false
  vars:
    ansible_network_os: junipernetworks.junos.junos
    ansible_connection: ansible.netcommon.network_cli
    # ansible_connection: ansible.netcommon.libssh
    # ansible_network_cli_ssh_type: libssh
    # ansible_libssh_ssh_type: libssh
    # ansible_network_cli_ssh_type: paramiko
    # ansible_libssh_password_prompt: "PASSCODE:"

  tasks:
    - name: Run show version on remote devices
      # ansible.netcommon.cli_command:
      junipernetworks.junos.junos_command:
        commands: show version
      register: command_output

    - name: Print gathered facts
      ansible.builtin.debug:
        msg: "{{ command_output }}"

...
